sudo: required
dist: trusty
language: perl
perl:
  - "5.18"
services:
  - postgresql
before_script:
  - psql -c 'create database openqa_test;' -U postgres
addons:
  postgresql: "9.6"
  chrome: stable
  ssh_known_hosts: github.com
  apt:
    packages:
      - libgmp3-dev
      - libdbus-1-dev
      - dbus-x11
env:
  global:
    - COMMIT_AUTHOR_EMAIL=skynet@open.qa
    - FULLSTACK=0 UITESTS=1
before_install:
  - cpanm local::lib
  - eval "$(perl -Mlocal::lib=${HOME}/perl_modules)"
  - mkdir -p $HOME/chrome
  - if ! test -f $HOME/chrome/chromedriver; then curl -s https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip | funzip - > $HOME/chrome/chromedriver; fi
  - chmod a+x $HOME/chrome/chromedriver
  - export PATH=$PATH:$HOME/chrome
install:
  - gem install sass
  - cpanm -nq --installdeps --with-feature=coverage .
script:
  - bash script/generate-documentation $encrypted_e2c381aa6b8c_key $encrypted_e2c381aa6b8c_iv
  - make travis-codecov
after_failure:
  - curl --upload-file /tmp/openqa-debug.log https://transfer.sh/openqa-debug.log
cache:
  directories:
    - $HOME/perl_modules
    - assets/cache
    - $HOME/chrome
